### ISSUE TITLE
Implement the note workflow

### ISSUE THREAD

**Issue by phaazon** [phaazon/toodoux#39]
We need to be able to add / edit notes.

**Comment by Sm03leBr00t** [comment]
like interactively? Because interactive mode would be something I miss

**Comment by phaazon** [comment]
No, this one is CLI only. However, interactive tasking is planned for a later version. However, what do you have on your mind @Sm03leBr00t about interactive notes?

**Comment by Sm03leBr00t** [comment]
Interactive in a way that it becomes more of a fluid todo workflow, with sel updating list, arrow or vim selection for tasks, a little like nano - idk if that helped but its my vision of a future toodoux

**Comment by phaazon** [comment]
Yeah, a TUI. It’s planned, but clearly not for now.

**Comment by phaazon** [comment]
This has been implemented in version [0.3](https://github.com/phaazon/toodoux/blob/master/CHANGELOG.md#03). Closing.
