### ISSUE TITLE
Add support for name filtering when listing tasks

### ISSUE THREAD

**Issue by phaazon** [phaazon/toodoux#51]
This is fairly easy to do as MVP, especially because all the work is already done: we already have the `name` and `metadata`.

For the name, we can simply put the words in a set and reduce the set as we read a task name (split into words too). Once we’re done, if the set is empty, then the task should be listed in; otherwise, filtered out.

**Comment by DarkDrek** [comment]
This can be closed now. Since #54 has been merged.
