### ISSUE TITLE
Add a way to sync todos between two PC

### ISSUE THREAD

**Issue by ArcticSpaceFox** [phaazon/toodoux#66]
## Should do

- syncing between nodes
- require no server
- maybe version control
- be secure (in a way that nobody can just download your todos or delete them)

## Ideas for syncing

- maybe work with IPFS to achieve syncing

**Comment by phaazon** [comment]
Thanks for opening this issue! So, quickly:

1. What do you mean?
2. What do you mean?
3. You can already use git to version your `tasks.json` file.
4. You can use `ssh` with `git`. TLS is secure enough to me.

**Comment by ArcticSpaceFox** [comment]
I mean an easy way to sync todos between pcs, no 3 steps just `td sync` and then it might sync via ipfs or smth to other pcs that share a key and the cid to the data. Just an idea no pressure though, convienience 👍

**Comment by chrisduerr** [comment]
It might be nice to be able to deploy toodoux as a service. So you have one instance running in your local network or the cloud which accepts synchronization requests from the clients running on various machines. You could even have a public instance where you can log in and if you're on a mobile device currently maybe look at it in your browser. I think that would provide a lot of value and it should be pretty simple to do.
