### ISSUE TITLE
Note UID is represented wrong

### ISSUE THREAD

**Issue by ArcticSpaceFox** [phaazon/toodoux#68]
## Problem

Looking at the notes for a task, it shows the UID incremented by one, this can be confusing to new users.

![image](https://user-images.githubusercontent.com/36639589/99512264-8dba7e80-2989-11eb-9365-87cf9779ac53.png)

**Comment by phaazon** [comment]
This is now fixed. Sorry for the delay. I’ll ship a new release soon.

**Comment by ArcticSpaceFox** [comment]
hey no worries
